services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: telegram_financas
      POSTGRES_PASSWORD: telegram_financas
      POSTGRES_DB: telegram_financas
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
